### ISSUE TITLE
Tricam FBD has incorrect location of `F_a`

### ISSUE THREAD

**Issue by larrykvit** [aaronksolomon/Cam-Forces#3]
The image in `triangle_force_diagram.png` is incorrect. The load `F_a` should not be applied at the top of the horn.

In a tricam, the sling or metal wire is attached to the top of the horn, but it is laying along the body. The force `F_a` should be the right contact point with `F_R,y`.

The reason why is because you do not model internal forces on a rigid FBD. You can envelope any area that is convenient to calculate the total forces acting on that body. So you include all of the sling up until the sling is right by the wall as part of the internal body.

An example of this is when doing beam calculations:
<img width="250" alt="internalforces-1" src="https://github.com/user-attachments/assets/caa68e2f-dc49-4cd1-9423-d945d5818865">
You can use the whole beam, or you can envelope only half of the beam and cut it half.

While it is interesting to have a comprehensive model, I think it overly complicates the analysis you are trying to do.

**Comment by aaronksolomon** [comment]
Thanks Larry, this makes a lot of sense, and makes sense. I'm not sure it's necessarily 'incorrect,' it's just a model that isn't accurate to a tricam. I did sort of want to look at the harder problem however (I think it relates to a general case for cams?) and to see how the general case is underconstrained. But agree with you that the way to get to an approx. with tricam is to have downward force acting on the right side (in this particular setup).

**Comment by larrykvit** [comment]
Sure, you can model the more general case. But having the load at the top of the triangle kinda makes the analysis harder than it should be. In a FBD a force can be moved along it direction of action. You currently use `r2` and `theta_2` to describe the position, but you can notice that in all of your results those variables show up as `r2 cos(theta_2)`, which is just the horizontal component.

The general case isn't that much harder, you just end up with one extra variable for the offset. It is a bit useful for cams like totem cams (since the load there is also offset), but with cams you don't have `F_R,y`. So the equations simplify for that case.

I added the general case analysis to my [google docs](https://docs.google.com/document/d/1qm05wCsLHl3v_bVg9r96nAhKPu47rz3BVG-xG1YPwKA/edit?usp=sharing)

The equation I get is the same as before but with the offset factor:

![image](https://github.com/user-attachments/assets/658feebf-3ce6-4572-a487-8dd6ed26a838)

For example, if the load (force applied) is halfway between the walls, then `k=0.5`. This will half the outward force. Since the load is the same, the friction force require is also the same. This doubles the requirements for the coefficient of friction.
